# Linear Regression Multiple Variables

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model 

In [2]:
df=pd.read_csv('house.csv')

In [3]:
df.head()

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [5]:
#Preprocessing to fill nan with median

In [7]:
import math
median_bedroom=math.floor(df.bedroom.median())
df.bedroom=df.bedroom.fillna(median_bedroom)

In [8]:
df.bedroom

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedroom, dtype: float64

In [9]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [10]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [11]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [12]:
reg.intercept_

383724.9999999998

In [13]:
reg.predict([[3000,3,40]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [18]:
(137.25*3000)-(26025.*3)-(6825.*40)+383724.9999999998

444399.9999999998

In [22]:
pip install word2number

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5583 sha256=87b2913c794b1a94f0bb1a6c07c57460cef4f9d4ac52a00f30f5d29b54a6864b
  Stored in directory: c:\users\huawei\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [20]:
#Exercise

In [23]:
from word2number import w2n 

In [42]:
df1=pd.read_csv('hiring1.csv')
df1


experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [43]:
df1.experience=df1.experience.fillna("zero")

In [44]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9   50000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [45]:
df1.experience=df1.experience.apply(w2n.word_to_num)

In [46]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    NaN                           7   72000
7          11                    7.0                           8   80000

In [47]:
median_test_score=math.floor(df1['test_score(out of 10)'].mean())
median_test_score

7

In [48]:
df1['test_score(out of 10)']=df1['test_score(out of 10)'].fillna(median_test_score)

In [49]:
df1['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [52]:
reg=linear_model.LinearRegression()
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary'])

LinearRegression()

In [53]:
reg.predict([[2,9,6]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])