In [2]:
#Elementswise operation

In [3]:
import numpy as np

In [4]:
x=np.array([[1,2,3],[4,5,6]], dtype=np.int16)

In [5]:
y=np.array([[7,8,9],[10,11,11]], dtype=np.int16)

In [6]:
print(x)

[[1 2 3]
 [4 5 6]]


In [7]:
print(y)

[[ 7  8  9]
 [10 11 11]]


In [8]:
print(x+y)

[[ 8 10 12]
 [14 16 17]]


In [9]:
print(np.add(x,y))

[[ 8 10 12]
 [14 16 17]]


In [10]:
print(x-y)

[[-6 -6 -6]
 [-6 -6 -5]]


In [11]:
print(np.subtract(x,y))

[[-6 -6 -6]
 [-6 -6 -5]]


In [12]:
print(x*y)

[[ 7 16 27]
 [40 55 66]]


In [13]:
print(np.multiply(x,y))

[[ 7 16 27]
 [40 55 66]]


In [14]:
print(x/y)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.54545455]]


In [15]:
print(np.divide(x,y))

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.54545455]]


In [16]:
print(x**2)

[[ 1  4  9]
 [16 25 36]]


In [17]:
print(np.sqrt(x))

[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]]


In [18]:
v=np.array([9,10])
w=np.array([10,11])

In [19]:
# Inner product of vector
print(v.dot(w))
print(w.dot(v))

200
200


In [20]:
print(np.dot(v,w))

200


In [21]:
#matrix*vector product
x=np.array([[1,2],[3,4]])
print(np.dot(x,v))

[29 67]


In [22]:
#matrix*matrix product
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(np.dot(x,y))

[[19 22]
 [43 50]]


In [23]:
#Transpose
print(x)
print()
print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [24]:
v=np.array([[9,10]])
print(v)
print()
print(v.T)

[[ 9 10]]

[[ 9]
 [10]]


In [25]:
x=np.array([[1,2],[3,4]])
for func in [x.min ,x.max, x.prod, x.sum, x.std, x.mean, x.var]:
    print(func.__name__,'=',func())

min = 1
max = 4
prod = 24
sum = 10
std = 1.118033988749895
mean = 2.5
var = 1.25


In [26]:
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(np.sum(x, axis=(0,1)))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
10


In [27]:
print(np.std(x))
print(np.std(x,axis=0))
print(np.std(x,axis=1))

1.118033988749895
[1. 1.]
[0.5 0.5]


In [28]:
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [29]:
# Broadcasting
#Fisrt rule
x=np.arange(5).reshape(1,1,5)

In [30]:
print(x)

[[[0 1 2 3 4]]]


In [31]:
y=np.array([1,2,3,4,5])

In [32]:
print(x.ndim)
print(y.ndim)

3
1


In [33]:
print(x+y)

[[[1 3 5 7 9]]]


In [34]:
# Second rule
x=np.arange(6).reshape(2,3)

In [35]:
print(x)

[[0 1 2]
 [3 4 5]]


In [36]:
y=np.array([[100],[200]])
print(y)

[[100]
 [200]]


In [37]:
print(x+y)
# sum x + [[100 , 100 , 100] [200, 200 , 200]]

[[100 101 102]
 [203 204 205]]


In [38]:
#combining rule 1&2
x=np.arange(6).reshape(2,3)
y=np.array([100,200,300])
print(x+y)

[[100 201 302]
 [103 204 305]]


In [39]:
z=np.array([1000])

In [40]:
print(x+z)

[[1000 1001 1002]
 [1003 1004 1005]]


In [41]:
#Third Rule

x=np.array([[1, 2, 3],
           [4 , 5, 6],
           [7 , 8, 9],
           [10,11,12]])

In [42]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
v=np.array([1,0,1])

In [44]:
y=np.empty_like(x)

In [45]:
for i in range(4):
    y[i,:]=x[i,:]+v

In [46]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [47]:
#simple way
y=v+x
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [48]:
#conditional operatoes
x=np.array([10,20,30,40])
print(x<[1,30,2,50])

[False  True False  True]


In [49]:
#broadcasting
print(x<25)

[ True  True False False]


In [50]:
print(x[x<25])#select elements from x that lower than 25

[10 20]


In [51]:
#Stacking Arrays

In [52]:
A=np.full((3,4),1.)

In [53]:
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
B=np.full((4,4),2.)
print(B)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [55]:
C=np.full((3,4), 3.)
print(C)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [56]:
print(np.vstack((A,B,C)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [57]:
print(np.hstack((A,C)))

[[1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]]


In [58]:
D=np.concatenate((A,B,C), axis=0)

In [59]:
print(D)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [60]:
#connect by increase dimension
E=np.stack((A,C))
print(E)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]


In [62]:
#Transposing array
F=np.arange(24).reshape(4,2,3)

In [63]:
print(F)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [67]:
#axis 0,1,2 (depth, height,weight)
B=F.transpose(1,2,0)

In [68]:
print(B)

[[[ 0  6 12 18]
  [ 1  7 13 19]
  [ 2  8 14 20]]

 [[ 3  9 15 21]
  [ 4 10 16 22]
  [ 5 11 17 23]]]


In [69]:
#Savin and Loading
A=np.random.rand(2,3)
print(A)
np.save("MYArray", A)

[[0.9670924  0.54393696 0.83045579]
 [0.41080942 0.564636   0.45654935]]


In [70]:
#load file
np.load("MYArray.npy")

array([[0.9670924 , 0.54393696, 0.83045579],
       [0.41080942, 0.564636  , 0.45654935]])

In [74]:
#Text format
np.savetxt('my_array.csv',A)

In [75]:
np.loadtxt("my_array.csv")

array([[0.9670924 , 0.54393696, 0.83045579],
       [0.41080942, 0.564636  , 0.45654935]])