In [7]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [8]:
df=pd.read_csv('house.csv')

In [9]:
df.head()

area    price
0  2600  5500000
1  3000  5650000
2  3200  6200000
3  3600  6800000
4  4000  7250000

In [10]:
model=LinearRegression()

In [11]:
model.fit(df[['area']],df.price)

LinearRegression()

In [12]:
model.coef_

array([1351.02739726])

In [13]:
model.intercept_

1848630.1369863022

In [14]:
model.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8603767.12328767])

In [15]:
#we use pickle library to allow us to serialize python object into a file

In [16]:
import pickle

In [17]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [19]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [20]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8603767.12328767])

In [21]:
#we can also use Sklearn joblib to save and load our model

In [28]:
import joblib

In [29]:
joblib.dump(model,'modelnamefile')

['modelnamefile']

In [30]:
mf=joblib.load('modelnamefile')

In [31]:
mf.predict([[4500]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7928253.42465753])

In [32]:
mf.coef_

array([1351.02739726])

In [33]:
mf.intercept_

1848630.1369863022